name: Hello World

on: 
  push:
    branches:
      - master  # Make sure this matches your branch name (e.g., 'main' or 'master')
  workflow_dispatch:  # Allows manual trigger

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
