name: "hello my name is sushant "


#for event use the on 

on: 
    push:
       branches: 
            -master 
            -production 


jobs: 
     hello-world: 
         runs-on: ubuntu-latest
         steps: 
          -name: "print hello sushant"
          -run : echo "hello sushant"            
