name: Hello World Workflow  # Name of the workflow

on: 
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  pull_request:  # Also runs on pull requests

jobs:
  hello_world:
    runs-on: ubuntu-latest  # Specifies the OS for running the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out the repository code

      - name: Print Hello World
        run: echo "Hello, World! GitHub Actions is running."  # Simple echo command
